### PR TITLE
Compatible with both underscore and lodash

### PR DESCRIPTION
**Pull request by mstrutt**
First up, really nice little tool, thanks for making it! Has been really useful in speeding up the project I've been working on.

Basically we use lodash instead of underscore and I ran into an issue when I used this with the latest version. I appreciate that you specifically say it's for use with underscore, but as it's just a one-liner to work with both I though it would be worth doing.

`.take` is an alias of `.first` in underscore, but in lodash `.first` is explicitly the first item, and `.take` is the first x items.

What do you think, worth a merge to maximise compatibility? :)

### CODE REVIEW

**Comment by pkaminski** [comment]
Sure, sounds good.  Wanna update the README as well to indicate that it'll also work with lodash now?  Thanks!

**Comment by mstrutt** [comment]
Good idea, have done that now :)

**Comment by pkaminski** [comment]
Thanks, merged!

**Comment by Sarkie** [comment]
@pkaminski should you update the bower version? (don't know)

**Comment by pkaminski** [comment]
Yeah, I probably should.  Done.

On Wed, Jun 3, 2015 at 4:36 AM, Sarkie notifications@github.com wrote:

> @pkaminski https://github.com/pkaminski should you update the bower
> version? (don't know)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pkaminski/digest-hud/pull/5#issuecomment-108321881.

## 

  Piotr Kaminski piotr@ideanest.com
  "That bun is dirty.  Don't eat that bun."

**Pull request merged**
