### PR TITLE
chore(deps): remove underscore dependency

### LINKED ISSUE #2: Remove underscore.js dependency
Would be great if this module didn't rely on underscore.js. There's just a handful of methods used so it shouldn't be too hard of a refactor. I'll try to make the change if time permits.

### PR DESCRIPTION
**Pull request by booleanbetrayal**
Resolves #2 

Since there wasn't a lot of complexity in what was being done with underscore, it was easy to convert to ES5 or angular convenience methods.

[Review on Reviewable](https://reviewable.io/reviews/pkaminski/digest-hud/8)

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
Let me know if you have any questions @pkaminski !

**Comment by pkaminski** [comment]
LGTM, thank you for doing this!  I'll merge and publish.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pkaminski/digest-hud/8)

**Comment by pkaminski** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pkaminski/digest-hud/8)

**Comment by booleanbetrayal** [comment]
:+1:

**Pull request merged**
